# -*- coding: utf-8 -*-
#"""sample_scrap.ipynb

#Automatically generated by Colaboratory.

#Original file is located at
# https://colab.research.google.com/drive/1UqKHKQahDQzLB6S7JLY5TGk8_q9WF4NF?usp=sharing
#"""

import requests
import csv
from bs4 import BeautifulSoup

url ="http://studyabroad.shiksha.com/usa/universities"

page = 1
csv_columns = ['University Name', 'University URL']
list_csv = []

while page < 3:
  resp = requests.get(url + '-' + str(page))
  soup = BeautifulSoup(resp.text)
  a = soup.findAll('a', {'class': 'font-15'})
  for i in a:
    list_csv.append({'University Name':i.text.strip(),'University URL':i.attrs['href']})
  page+=1

with open('college_list_usa.csv', 'w') as file:
    w = csv.DictWriter(file, fieldnames=csv_columns)
    w.writeheader()
    for data in list_csv:
            w.writerow(data)

for i in range(30):
  num = 0
  print(list_csv[i]['University Name'], i)
  rl = list_csv[i]['University URL'] + '/courses'
  col = ['Course Name', 'Duration', '1st year tution fess', 'GMAT', 'GRE', 'TOEFL', 'IELTS', 'SAT', "PTE", "Application Deadline"]
  csv_ls = []
  x = requests.get(rl)
  sp = BeautifulSoup(x.text)
  div = []
  while sp.find('div',{'class':'content-wrap clearfix'+str(num)}) != None:
    div.append(sp.find('div',{'class':'content-wrap clearfix'+str(num)}))
    num+=1
  for j in div:
    dicts = {'Course Name':'-', 'Duration':'-', '1st year tution fess':'-', 'GMAT':'-', 'GRE':'-', 'TOEFL':'-', 'IELTS':'-', 'SAT':'-', 'PTE':'-', 'Application Deadline':'-'}
    dicts['Course Name'] = j.findAll('a')[0]['title']
    a_url = j.findAll('a')[0]['href']
    ot = j.findAll('div')
    dicts['Duration'] = ot[2].find('p').text
    dicts['1st year tution fess'] = ot[3].find('p').text
    y = requests.get('https://studyabroad.shiksha.com' + a_url)
    sp2 = BeautifulSoup(y.text)
    tab = sp2.findAll('div', {'class':'Styled__WidgetCard-opouq6-0'})
    for s in tab:
      if 'Entry Requirements' in s.text:
        lb = s.findAll('label')
        break
    for s in tab:
      if 'Application Process' in s.text:
        acc = s.findAll('div', {'class':'Styled__AccordianBox-sc-14wej5r-18'})
        break

    '''for d in acc:
      if 'Application deadline' in d.text:
        p = d.find('p', {'class':'Styled__AccordianParagraph-sc-14wej5r-25'})
        dicts['Application Deadline'] = p.text'''
    
    
    for l in range(len(lb)):
      label = lb[l].text.split(' ')
      dicts[label[0].strip()] = lb[l].findNext('span').text.strip()

    d_k = list(dicts.keys())
    for o in d_k:
      if o not in col:
        del dicts[o]
        
    csv_ls.append(dicts)
    print(csv_ls)
  with open(list_csv[i]['University Name']+'_courses.csv', 'w') as file:
    w = csv.DictWriter(file, fieldnames=col)
    w.writeheader()
    for data in csv_ls:
            w.writerow(data)
  file.close()

# !zip -r /content/ireland.zip /content/ireland